/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'age' : bigint,
  'service' : string,
  'status' : AppointmentStatus,
  'cnic' : string,
  'appointmentDate' : string,
  'appointmentTime' : string,
  'gender' : string,
  'notes' : string,
  'patientName' : string,
  'phone' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Invoice {
  'id' : bigint,
  'status' : InvoiceStatus,
  'createdAt' : string,
  'totalAmount' : bigint,
  'patientName' : string,
  'phone' : string,
  'items' : Array<InvoiceItem>,
}
export interface InvoiceItem { 'description' : string, 'amount' : bigint }
export type InvoiceStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addService' : ActorMethod<[string, string, bigint], bigint>,
  'createAppointment' : ActorMethod<[Appointment], bigint>,
  'createInvoice' : ActorMethod<[Invoice], bigint>,
  'deleteAppointment' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAppointmentById' : ActorMethod<[bigint], Appointment>,
  'getInvoiceById' : ActorMethod<[bigint], Invoice>,
  'markInvoiceAsPaid' : ActorMethod<[bigint], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];