/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'service' : IDL.Text,
  'status' : AppointmentStatus,
  'cnic' : IDL.Text,
  'appointmentDate' : IDL.Text,
  'appointmentTime' : IDL.Text,
  'gender' : IDL.Text,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const InvoiceItem = IDL.Record({
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
  'createdAt' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
  'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getInvoiceById' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'markInvoiceAsPaid' : IDL.Func([IDL.Nat], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'service' : IDL.Text,
    'status' : AppointmentStatus,
    'cnic' : IDL.Text,
    'appointmentDate' : IDL.Text,
    'appointmentTime' : IDL.Text,
    'gender' : IDL.Text,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const InvoiceItem = IDL.Record({
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
    'createdAt' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'createAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
    'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getInvoiceById' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'markInvoiceAsPaid' : IDL.Func([IDL.Nat], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };